connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: e2n0c0m2p

development:
  <<: *connection
  database: vet_clinic

test:
  <<: *connection
  database: vet_clinic

production:
  <<: *connection
  database: vet_clinic
